config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index' 
  resources :mercs
  resources :tipo_mercs
  resources :tipo_negs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merc.rb
class Merc < ApplicationRecord
	belongs_to :TipoMerc
	belongs_to :TipoNeg
	validates_presence_of :merc_nome
	validates_presence_of :TipoMerc_id
	validates_presence_of :qtde
	validates_presence_of :preco
	validates_presence_of :TipoNeg_id
	validates_numericality_of :TipoMerc_id
	validates_numericality_of :qtde
	validates_numericality_of :preco
	validates_numericality_of :TipoNeg_id
		validates_uniqueness_of :TipoMerc_id
end

app/models/tipo_merc.rb
class TipoMerc < ApplicationRecord
	has_many :Merc
	validates_presence_of :descricao
	validates_uniqueness_of :descricao
end

app/models/tipo_neg.rb
class TipoNeg < ApplicationRecord
	has_many :Merc
		validates_presence_of :descricao
			validates_uniqueness_of :descricao
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mercs_controller.rb
class MercsController < ApplicationController
  before_action :set_merc, only: [:show, :edit, :update, :destroy]

  # GET /mercs
  # GET /mercs.json
  def index
    @mercs = Merc.all
  end

  # GET /mercs/1
  # GET /mercs/1.json
  def show
  end

  # GET /mercs/new
  def new
    @merc = Merc.new
  end

  # GET /mercs/1/edit
  def edit
  end

  # POST /mercs
  # POST /mercs.json
  def create
    @merc = Merc.new(merc_params)

    respond_to do |format|
      if @merc.save
        format.html { redirect_to @merc, notice: 'Merc was successfully created.' }
        format.json { render :show, status: :created, location: @merc }
      else
        format.html { render :new }
        format.json { render json: @merc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mercs/1
  # PATCH/PUT /mercs/1.json
  def update
    respond_to do |format|
      if @merc.update(merc_params)
        format.html { redirect_to @merc, notice: 'Merc was successfully updated.' }
        format.json { render :show, status: :ok, location: @merc }
      else
        format.html { render :edit }
        format.json { render json: @merc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mercs/1
  # DELETE /mercs/1.json
  def destroy
    @merc.destroy
    respond_to do |format|
      format.html { redirect_to mercs_url, notice: 'Merc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merc
      @merc = Merc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merc_params
      params.require(:merc).permit(:TipoMerc_id, :merc_nome, :qtde, :preco, :TipoNeg_id)
    end
end

app/controllers/tipo_mercs_controller.rb
class TipoMercsController < ApplicationController
  before_action :set_tipo_merc, only: [:show, :edit, :update, :destroy]

  # GET /tipo_mercs
  # GET /tipo_mercs.json
  def index
    @tipo_mercs = TipoMerc.all
  end

  # GET /tipo_mercs/1
  # GET /tipo_mercs/1.json
  def show
  end

  # GET /tipo_mercs/new
  def new
    @tipo_merc = TipoMerc.new
  end

  # GET /tipo_mercs/1/edit
  def edit
  end

  # POST /tipo_mercs
  # POST /tipo_mercs.json
  def create
    @tipo_merc = TipoMerc.new(tipo_merc_params)

    respond_to do |format|
      if @tipo_merc.save
        format.html { redirect_to @tipo_merc, notice: 'Tipo merc was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_merc }
      else
        format.html { render :new }
        format.json { render json: @tipo_merc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_mercs/1
  # PATCH/PUT /tipo_mercs/1.json
  def update
    respond_to do |format|
      if @tipo_merc.update(tipo_merc_params)
        format.html { redirect_to @tipo_merc, notice: 'Tipo merc was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_merc }
      else
        format.html { render :edit }
        format.json { render json: @tipo_merc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_mercs/1
  # DELETE /tipo_mercs/1.json
  def destroy
    @tipo_merc.destroy
    respond_to do |format|
      format.html { redirect_to tipo_mercs_url, notice: 'Tipo merc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_merc
      @tipo_merc = TipoMerc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_merc_params
      params.require(:tipo_merc).permit(:descricao)
    end
end

app/controllers/tipo_negs_controller.rb
class TipoNegsController < ApplicationController
  before_action :set_tipo_neg, only: [:show, :edit, :update, :destroy]

  # GET /tipo_negs
  # GET /tipo_negs.json
  def index
    @tipo_negs = TipoNeg.all
  end

  # GET /tipo_negs/1
  # GET /tipo_negs/1.json
  def show
  end

  # GET /tipo_negs/new
  def new
    @tipo_neg = TipoNeg.new
  end

  # GET /tipo_negs/1/edit
  def edit
  end

  # POST /tipo_negs
  # POST /tipo_negs.json
  def create
    @tipo_neg = TipoNeg.new(tipo_neg_params)

    respond_to do |format|
      if @tipo_neg.save
        format.html { redirect_to @tipo_neg, notice: 'Tipo neg was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_neg }
      else
        format.html { render :new }
        format.json { render json: @tipo_neg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_negs/1
  # PATCH/PUT /tipo_negs/1.json
  def update
    respond_to do |format|
      if @tipo_neg.update(tipo_neg_params)
        format.html { redirect_to @tipo_neg, notice: 'Tipo neg was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_neg }
      else
        format.html { render :edit }
        format.json { render json: @tipo_neg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_negs/1
  # DELETE /tipo_negs/1.json
  def destroy
    @tipo_neg.destroy
    respond_to do |format|
      format.html { redirect_to tipo_negs_url, notice: 'Tipo neg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_neg
      @tipo_neg = TipoNeg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_neg_params
      params.require(:tipo_neg).permit(:descricao)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mercs_helper.rb
module MercsHelper
end

app/helpers/tipo_mercs_helper.rb
module TipoMercsHelper
end

app/helpers/tipo_negs_helper.rb
module TipoNegsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de controle de mercadorias</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mercs/_form.html.erb
<%= form_for(merc) do |f| %>
  <% if merc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merc.errors.count, "error") %> prohibited this merc from being saved:</h2>

      <ul>
      <% merc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-box padding-formbox">
   <h1> <center>Cadastro de Mercadorias </center></h1>
 <h1> <label for="merc_TipoMerc_id">Tipo de Mercadoria</label></h1>
    <input name="merc[TipoMerc_id]" id="merc_TipoMerc_id" class="input" type="number">

  
   <h1> <label for="merc_merc_nome">Nome da Mercadoria</label></h1><h1>
    <input name="merc[merc_nome]" class="input" id="merc_merc_nome" type="text"> 


   <h1> <label for="merc_qtde">Qtde</label></h1>
    <input name="merc[qtde]" class="input" id="merc_qtde" type="number">
 

  
   <h1> <label for="merc_preco">Preco</label></h1>
    <input name="merc[preco]" class="input" id="merc_preco" type="text">



   <h1> <label for="merc_TipoNeg_id">Tipo de Negociação</label> </h1>
    <input name="merc[TipoNeg_id]" class="input" id="merc_TipoNeg_id" type="number">
  

 
    <h2><input name="commit" class="botao_submit" type="submit" onclick="return validar()" value="Submeter" ></h2>
     <center><a href="/mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
  </div>
<% end %>

app/views/mercs/_form2.html.erb
<%= form_for(merc) do |f| %>
  <% if merc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_neg_url.errors.count, "error") %> prohibited this tipo_neg from being saved:</h2>

      <ul>
      <% tipo_neg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-box padding-formbox">
    <h1><%= f.label :TipoMerc_id %></h1>
    <%= f.text_field :TipoMerc_id %>
  
     <h1> <%= f.label :merc_nome%></h1>
    <%= f.text_field :merc_nome %>

        <h1>  <%= f.label :qtde%></h1>
    <%= f.text_field :qtde %>

     <h1><%= f.label :preco%></h1>
    <%= f.text_field :preco%>

     <h1>     <%= f.label :TipoNeg_id%></h1>
    <%= f.number_field :TipoNeg_id %>
 
    <h2><input name="commit" class="botao_submit" type="submit" value="Editar" data-disable-with="Create Merc"></h2>
     <center><a href="/mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
  </div>

<% end %>

app/views/mercs/edit.html.erb
<h1>Editing Merc</h1>

<%= render 'form2', merc: @merc %>

app/views/mercs/index.html.erb
<p id="notice"><%= notice %></p>
<div class ="form-box padding-formbox">
        
         
      
<h1><center>Mercadorias</center></h1>
<br><br>
<table>
  <thead>
    <tr>
      <th>Tipo de Mercadoria</th>
      <th>Merc nome</th>
      <th>Qtde</th>
      <th>Preco</th>
      <th>Tiponeg</th>
       <td>  <br><%= link_to 'Cadastrar nova mercadoria', new_merc_path %> </td>

    </tr>
  </thead>

  <tbody>
   <% @mercs.each_with_index do |merc,index| %>
      <tr>
   
        <td><%= merc.TipoMerc_id %></td>
        <td><%= merc.merc_nome %></td>
        <td><%= merc.qtde %></td>
        <td><%= merc.preco %></td>
        <td><%= merc.TipoNeg_id %></td>
              <td> <br><%= link_to 'Atualizar Mercadorias', edit_merc_path(merc) %></td>
         <td> <br><%= link_to 'Deletar mercadorias', merc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
      </tr>

</tbody>

       <% if index == @mercs.size - 1 %>
<tr>
      <td>  <br><%= link_to 'Cadastrar nova mercadoria', new_merc_path %> </td>

       
        
       <% end %>
       </tr>

<% end %>
      
     
  
</table>
<br> <br> <center><a href="/" class="a"><span style="color: #54cdc3"> Voltar ao menu</span></a></center></td>

  

  </div>

app/views/mercs/new.html.erb
<h1>New Merc</h1>

<%= render 'form', merc: @merc %>

app/views/mercs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipomerc:</strong>
  <%= @merc.TipoMerc_id %>
</p>

<p>
  <strong>Merc nome:</strong>
  <%= @merc.merc_nome %>
</p>

<p>
  <strong>Qtde:</strong>
  <%= @merc.qtde %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @merc.preco %>
</p>

<p>
  <strong>Tiponeg:</strong>
  <%= @merc.TipoNeg_id %>
</p>


     <center><a href="/mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>

app/views/tipo_mercs/_form.html.erb
<%= form_for(tipo_merc) do |f| %>
  <% if tipo_merc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_merc.errors.count, "error") %> prohibited this tipo_merc from being saved:</h2>

      <ul>
      <% tipo_merc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-box padding-formbox">
   <h1> <center>Cadastro de Tipos de Mercadoria </center></h1>
   <h1> <label for="tipo_merc_descricao">Descrição</label></h1>
    <input name="tipo_merc[descricao]" id="tipo_merc_descricao" type="text">
  </div>


    <div class="actions">
   <h2><input name="commit" class="botao_submit" type="submit" value="Submeter" ></h2>
     <center><a href="/tipo_mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
     </div>
</form>
<% end %>

app/views/tipo_mercs/_form2.html.erb
<%= form_for(tipo_merc) do |f| %>
  <% if tipo_merc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_merc.errors.count, "error") %> prohibited this tipo_merc from being saved:</h2>

      <ul>
      <% tipo_merc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="form-box padding-formbox">
   <h1> <center>Atualização de tipos de mercadorias </center></h1>
    <h1> <%= f.label :descricao%></h1>
    <%= f.text_field :descricao %>
  </div>



    <div class="actions">
   <h2><input name="commit" class="botao_submit" type="submit" value="Submeter" ></h2>
     <center><a href="/tipo_mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
     </div>
</form>
<% end %>

app/views/tipo_mercs/edit.html.erb
<h1>Editing Tipo Merc</h1>

<%= render 'form2', tipo_merc: @tipo_merc %>

app/views/tipo_mercs/index.html.erb
<p id="notice"><%= notice %></p>
<div class ="form-box padding-formbox">
<h1>Tipos de Mercadoria</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
      <td>  <br><%= link_to 'Cadastrar novo tipo de  mercadoria', new_tipo_merc_path %> 
    </tr>
  </thead>

  <tbody>
    <% @tipo_mercs.each_with_index do |tipo_merc,index| %>
      <tr>
        <td><%= tipo_merc.descricao %></td>
          <td> <%= link_to 'Atualizar Tipos de Mercadorias', edit_tipo_merc_path(tipo_merc) %></td>
         <td> <br><%= link_to 'Deletar Tipos de mercadorias', tipo_merc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
      </tr>
    
  </tbody>

    <% if index == @tipo_mercs.size - 1 %>
<tr>
      <td>  <br><%= link_to 'Cadastrar novo tipo de  mercadoria', new_tipo_merc_path %> </td>
      
      
       
        
         <% end %>
       </tr>

<% end %>
      
     </th>
  
</table>
<br> <br> <center><a href="/" class="a"><span style="color: #54cdc3"> Voltar ao menu</span></a></center></td>

  

  </div>

app/views/tipo_mercs/new.html.erb
<h1>New Tipo Merc</h1>

<%= render 'form', tipo_merc: @tipo_merc %>

app/views/tipo_mercs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_merc.descricao %>
</p>

<br> <br> <center><a href="/tipo_mercs" class="a"><span style="color: #54cdc3"> Voltar ao menu</span></a></center></td>

app/views/tipo_negs/_form.html.erb
<%= form_for(tipo_neg) do |f| %>
  <% if tipo_neg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_neg.errors.count, "error") %> prohibited this tipo_neg from being saved:</h2>

      <ul>
      <% tipo_neg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-box padding-formbox">
   <h1> <center>Cadastro de Tipos de Negociação </center></h1>
   <h1> <label for="tipo_neg_descricao">Descricao</label></h1>
    <input name="tipo_neg[descricao]" id="tipo_neg_descricao" type="text">
  </div>

  <div class="actions">
   <h2><input name="commit" class="botao_submit" type="submit" value="Submeter" ></h2>
     <center><a href="/tipo_negs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
</form>
<% end %>

app/views/tipo_negs/_form2.html.erb
<%= form_for(tipo_neg) do |f| %>
  <% if tipo_neg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_neg.errors.count, "error") %> prohibited this tipo_neg from being saved:</h2>

      <ul>
      <% tipo_neg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-box padding-formbox">
   <h1> <center>Atualização de Tipos de Negociação </center></h1>
    <h1> <%= f.label :descricao%></h1>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
   <h2><input name="commit" class="botao_submit" type="submit" value="Submeter" ></h2>
     <center><a href="/tipo_negs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>
</form>
<% end %>

app/views/tipo_negs/edit.html.erb
<h1>Editar Tipo de Negociação</h1>

<%= render 'form2', tipo_neg: @tipo_neg %>


     

app/views/tipo_negs/index.html.erb
<p id="notice"><%= notice %></p>


<div class ="form-box padding-formbox">
<h1>Tipo de Negociações</h1>
<table>
  <thead>
    <tr width=100%>
      <th>Descricao</th>
       <th> <td>  <br><%= link_to 'Cadastrar novos Tipos de negociações', new_tipo_neg_path %> </th>
 </tr>
 
    
  </thead>

  <tbody>
    <% @tipo_negs.each_with_index do |tipo_neg,index| %>
      <tr>
        <td><%= tipo_neg.descricao %></td>
           <td> <%= link_to 'Atualizar Tipos de negociações', edit_tipo_neg_path(tipo_neg) %></td>
         <td> <br><%= link_to 'Deletar Tipos de negociações', tipo_neg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
  
  </tbody>

       <% if index == @tipo_negs.size - 1 %>
<tr>
      <td>  <br><%= link_to 'Cadastrar novos Tipos de negociações', new_tipo_neg_path %> </td>
      
      
       
        
         <% end %>
       </tr>

<% end %>
      
     </th>
  
</table>
<br> <br> <center><a href="/" class="a"><span style="color: #54cdc3"> Voltar ao menu</span></a></center></td>

  

  </div>

app/views/tipo_negs/new.html.erb
<%= render 'form', tipo_neg: @tipo_neg %>

app/views/tipo_negs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_neg.descricao %>
</p>

     <center><a href="/mercs" class="a"><span style="color: #54cdc3"> Voltar </span></a></center>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<div class ="form-box padding-formbox">
<h1> <center><a href="/mercs" font-size:36px class="a"><span style="color: #54cdc3"> Controle de Mercadorias </span></a></center></h1>
</div>
<div class ="form-box-2 padding-formbox">
<h1> <center><a color:FFF href="/tipo_mercs" font-size:36px class="a"><span style="color: #54cdc3"> Controle de Tipos de Mercadorias </span></a></center></h1>
</div>
<div class ="form-box-2 padding-formbox">
<h1> <center><a color:FFF href="/tipo_negs" font-size:36px class="a"><span style="color: #54cdc3"> Controle de Tipos de Negociação </span></a></center></h1>
</div>